#!/usr/bin/env python3
"""Stage 7: Generate AlN-on-Si(111) deposition inputs (LAMMPS, using the trained
NEP via pair_style nep) for every condition in config/criteria.yaml's
deposition_sweep.

The substrate is a Si(111) slab from aln_si_structures.py. Al and N arrive as
two separate `fix deposit` streams whose rates are set by the total flux and the
V/III ratio (deposition_sweep.n_to_al_ratio). Each species gets the incident
velocity that matches the requested kinetic energy for its own mass, tilted by
the incident angle in the x-z plane. One LAMMPS data file + in.deposit script
is written per (temperature, energy, angle, flux, N/Al ratio) combination under
deposition/sim_inputs/<condition_id>/.

Slab layout: the bottom Si bilayer is frozen, the rest of the substrate is
thermostatted at the substrate temperature, and deposited atoms evolve NVE so
impact energy dissipates into the substrate rather than being thermostatted away.

pair_style nep requires a LAMMPS build with the NEP plugin
(https://github.com/brucefan1983/NEP_CPU), see references/hpc_notes.md.
Deposition MD runs at rates far above experiment, so treat temperature as an
effective parameter and check results against the measured target.
"""
from __future__ import annotations

import argparse
import itertools
import math
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
from _common import ConfigError, DEPOSITION_DIR, eprint, read_json, write_json

SPECIES = ["Al", "N", "Si"]           # LAMMPS atom types 1, 2, 3
MASSES = {"Al": 26.9815, "N": 14.0067, "Si": 28.0855}
TIMESTEP_PS = 0.001

# Substrate: 8x8 Si(111) surface cells (~30.7 A wide), 6 bilayers = 768 atoms
SLAB_REPEAT, SLAB_BILAYERS = 8, 6
FROZEN_BILAYERS = 1
INSERT_HEIGHT_A = (15.0, 20.0)        # insertion window above the slab surface
BOX_TOP_MARGIN_A = 25.0


def _require_ase():
    try:
        import ase  # noqa: F401
    except ImportError as e:
        raise ConfigError("ASE is required (`pip install ase`) to build the substrate slab.") from e


def build_substrate_slab():
    from aln_si_structures import si111_slab

    slab = si111_slab(SLAB_REPEAT, SLAB_BILAYERS)
    top = slab.positions[:, 2].max()
    cell = slab.cell.array.copy()
    cell[2] = [0.0, 0.0, top + BOX_TOP_MARGIN_A]
    slab.set_cell(cell)
    slab.pbc = (True, True, False)
    return slab


def incident_speed_A_per_ps(energy_eV: float, mass_amu: float) -> float:
    """E = m v^2 / 2 in LAMMPS metal units: 1 eV/amu = 9648.53 A^2/ps^2."""
    return math.sqrt(2.0 * energy_eV * 9648.53 / mass_amu)


def write_lammps_data(path: Path, atoms):
    from ase.io import write

    write(path, atoms, format="lammps-data", specorder=SPECIES, masses=True, units="metal")


def write_in_deposit(path: Path, *, data_file: str, nep_file: str, slab_top: float,
                     frozen_top: float, temperature_K: float, incident_energy_eV: float,
                     incident_angle_deg: float, flux_atoms_per_ps: float,
                     n_to_al_ratio: float, n_deposit_atoms: int = 400):
    # Split the total flux and atom count between Al and N by the V/III ratio
    al_frac = 1.0 / (1.0 + n_to_al_ratio)
    n_al = max(1, round(n_deposit_atoms * al_frac))
    n_n = max(1, n_deposit_atoms - n_al)
    steps_al = max(1, round(1.0 / (flux_atoms_per_ps * al_frac * TIMESTEP_PS)))
    steps_n = max(1, round(1.0 / (flux_atoms_per_ps * (1.0 - al_frac) * TIMESTEP_PS)))
    run_steps = max(n_al * steps_al, n_n * steps_n) + 20000   # + 20 ps to settle

    theta = math.radians(incident_angle_deg)

    def velocity_args(symbol):
        v = incident_speed_A_per_ps(incident_energy_eV, MASSES[symbol])
        vz, vx = -v * math.cos(theta), v * math.sin(theta)
        return f"vz {vz:.4f} {vz:.4f} vx {vx:.4f} {vx:.4f}"

    zlo, zhi = slab_top + INSERT_HEIGHT_A[0], slab_top + INSERT_HEIGHT_A[1]
    species_str = " ".join(SPECIES)

    content = f"""# AlN on Si(111): T={temperature_K} K, E_inc={incident_energy_eV} eV, \
angle={incident_angle_deg} deg, flux={flux_atoms_per_ps}/ps, N/Al={n_to_al_ratio}
# Generated by generate_deposition_simulation.py

units metal
atom_style atomic
boundary p p f

read_data {data_file}

pair_style nep
pair_coeff * * {nep_file} {species_str}

region frozen block INF INF INF INF INF {frozen_top:.3f} units box
region deposit_region block INF INF INF INF {zlo:.3f} {zhi:.3f} units box
group frozen region frozen
group substrate subtract all frozen
group addatoms empty

velocity substrate create {temperature_K} 12345 dist gaussian
fix freeze frozen setforce 0.0 0.0 0.0
velocity frozen set 0.0 0.0 0.0
fix nvt_sub substrate nvt temp {temperature_K} {temperature_K} 0.1
fix nve_add addatoms nve

# Al (type 1) and N (type 2) streams; velocities in A/ps from E_inc and each mass
fix depAl addatoms deposit {n_al} 1 {steps_al} 1111 region deposit_region near 2.0 attempt 50 &
    {velocity_args("Al")} units box
fix depN addatoms deposit {n_n} 2 {steps_n} 2222 region deposit_region near 2.0 attempt 50 &
    {velocity_args("N")} units box

# Atoms reflected or sputtered past the top of the box are removed
thermo_modify lost ignore flush yes

timestep {TIMESTEP_PS}
thermo 1000
thermo_style custom step temp pe ke etotal atoms

dump traj all custom 5000 traj.lammpstrj id type x y z vx vy vz
run {run_steps}

write_data final_state.data
"""
    path.write_text(content)


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.parse_args()

    _require_ase()

    setup_path = DEPOSITION_DIR / "setup.json"
    if not setup_path.exists():
        raise ConfigError(f"{setup_path} not found -- run identify_deposition_setup.py first.")
    setup = read_json(setup_path)

    sweep = setup["sweep"]
    nep_path = Path(setup["nep_potential_path"])

    slab = build_substrate_slab()
    slab_top = slab.positions[:, 2].max()
    # Each bilayer is a/sqrt(3) = 3.135 A thick; freeze the bottom one(s)
    frozen_top = slab.positions[:, 2].min() + FROZEN_BILAYERS * 3.135 - 0.1

    sim_inputs_dir = DEPOSITION_DIR / "sim_inputs"
    sim_inputs_dir.mkdir(parents=True, exist_ok=True)

    combos = list(itertools.product(
        sweep["temperature_K"], sweep["incident_energy_eV"],
        sweep["incident_angle_deg"], sweep["flux_atoms_per_ps"],
        sweep.get("n_to_al_ratio", [1.0]),
    ))

    manifest = []
    for temp, energy, angle, flux, ratio in combos:
        cond_id = f"T{temp}_E{energy}_A{angle}_F{flux}_R{ratio}"
        cond_dir = sim_inputs_dir / cond_id
        cond_dir.mkdir(parents=True, exist_ok=True)

        write_lammps_data(cond_dir / "structure.data", slab)
        (cond_dir / "nep.txt").write_text(nep_path.read_text())
        write_in_deposit(
            cond_dir / "in.deposit",
            data_file="structure.data", nep_file="nep.txt",
            slab_top=slab_top, frozen_top=frozen_top,
            temperature_K=temp, incident_energy_eV=energy, incident_angle_deg=angle,
            flux_atoms_per_ps=flux, n_to_al_ratio=ratio,
        )
        manifest.append({
            "condition_id": cond_id,
            "temperature_K": temp, "incident_energy_eV": energy,
            "incident_angle_deg": angle, "flux_atoms_per_ps": flux,
            "n_to_al_ratio": ratio,
            "dir": str(cond_dir),
        })

    write_json(sim_inputs_dir / "manifest.json", {"conditions": manifest, "species": SPECIES})
    print(f"[generate_deposition_simulation] Wrote {len(manifest)} deposition condition(s) to {sim_inputs_dir}")


if __name__ == "__main__":
    try:
        main()
    except ConfigError as e:
        eprint(f"[generate_deposition_simulation] CONFIG ERROR: {e}")
        sys.exit(2)
