#!/usr/bin/env python3
"""Stage 2: Submit VASP jobs (single-point / short AIMD) for the structures
generated by generate_structures.py, on either Anvil or ACES.

For each structure in round_XXX/structures/, this stage:
  1. Writes VASP inputs (INCAR, KPOINTS, POSCAR already exists, POTCAR) into
     round_XXX/vasp/<structure_id>/
  2. Renders and submits an sbatch script per structure (or you can adapt
     _submit_one to batch several structures per job if your queue charges by
     job count rather than core-hours -- left as a single-structure-per-job
     default since VASP walltime varies a lot by structure size)
  3. Records job ids to round_XXX/vasp/job_ids.json so later stages / the
     orchestrator can poll completion.

POTCAR requires licensed VASP pseudopotentials that this skill cannot ship or
fetch. Set the VASP_PP_PATH environment variable to your local POTCAR
directory (ase's convention: $VASP_PP_PATH/potpaw_PBE/<Element>/POTCAR) before
running this stage -- see references/hpc_notes.md.
"""
from __future__ import annotations

import argparse
import os
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
from _common import (
    ConfigError,
    cluster_config,
    eprint,
    read_json,
    render_template,
    require_filled,
    round_dir,
    sbatch_context,
    submit_job,
    write_json,
)

DEFAULT_INCAR_SINGLE_POINT = {
    "PREC": "Accurate",
    "ENCUT": 520,
    "EDIFF": 1e-6,
    "ISMEAR": 0,
    "SIGMA": 0.05,
    "IBRION": -1,   # no ionic relaxation -- single-point energy/force/stress for NEP training
    "NSW": 0,
    "LWAVE": False,
    "LCHARG": False,
    "LREAL": "Auto",
    "ISYM": 0,      # keep symmetry off so rattled/off-equilibrium structures aren't misassigned
}


def write_incar(path: Path, overrides: dict | None = None):
    tags = dict(DEFAULT_INCAR_SINGLE_POINT)
    if overrides:
        tags.update(overrides)
    lines = []
    for k, v in tags.items():
        if isinstance(v, bool):
            v = ".TRUE." if v else ".FALSE."
        lines.append(f"{k} = {v}")
    path.write_text("\n".join(lines) + "\n")


def write_kpoints(path: Path, mesh=(3, 3, 3)):
    path.write_text(
        "Automatic mesh\n0\nGamma\n"
        f"{mesh[0]} {mesh[1]} {mesh[2]}\n0 0 0\n"
    )


def write_potcar(structure_dir: Path, poscar_path: Path):
    pp_path = os.environ.get("VASP_PP_PATH")
    if not pp_path:
        raise ConfigError(
            "VASP_PP_PATH is not set. POTCAR files are licensed VASP "
            "pseudopotentials this skill cannot generate or fetch -- set "
            "VASP_PP_PATH to your local pseudopotential directory (see "
            "references/hpc_notes.md) and re-run this stage."
        )
    try:
        from ase.io import read
        from ase.calculators.vasp import Vasp
    except ImportError as e:
        raise ConfigError("ASE with VASP support is required (`pip install ase`).") from e

    atoms = read(poscar_path)
    elements = list(dict.fromkeys(atoms.get_chemical_symbols()))  # unique, order-preserved
    potcar_dir = Path(pp_path) / "potpaw_PBE"
    missing = [el for el in elements if not (potcar_dir / el / "POTCAR").exists()]
    if missing:
        raise ConfigError(
            f"POTCAR not found under {potcar_dir} for element(s): {missing}. "
            f"Check VASP_PP_PATH and that you have the pseudopotential set "
            f"installed for these elements."
        )
    with open(structure_dir / "POTCAR", "w") as out:
        for el in elements:
            out.write((potcar_dir / el / "POTCAR").read_text())


def stage_structure(structure_id: str, poscar_src: Path, vasp_round_dir: Path) -> Path:
    structure_dir = vasp_round_dir / structure_id
    structure_dir.mkdir(parents=True, exist_ok=True)
    (structure_dir / "POSCAR").write_text(poscar_src.read_text())
    write_incar(structure_dir / "INCAR")
    write_kpoints(structure_dir / "KPOINTS")
    write_potcar(structure_dir, poscar_src)
    return structure_dir


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--round", type=int, required=True)
    parser.add_argument("--cluster", choices=["anvil", "aces"], required=True)
    parser.add_argument("--dry-run", action="store_true",
                         help="Write inputs and render sbatch scripts but don't call sbatch")
    args = parser.parse_args()

    cfg = cluster_config(args.cluster)
    require_filled(cfg, context=f"submit_vasp.py --cluster {args.cluster}")

    r_dir = round_dir(args.round)
    manifest = read_json(r_dir / "structures_manifest.json")

    vasp_round_dir = r_dir / "vasp"
    vasp_round_dir.mkdir(parents=True, exist_ok=True)

    job_ids = {}
    for entry in manifest["structures"]:
        structure_id = entry["id"]
        poscar_src = Path(entry["path"])
        try:
            structure_dir = stage_structure(structure_id, poscar_src, vasp_round_dir)
        except ConfigError:
            raise  # stop the whole stage -- POTCAR/VASP_PP_PATH problems apply to every structure
        except Exception as e:
            eprint(f"[submit_vasp] Skipping {structure_id}: failed to stage inputs ({e})")
            continue

        ctx = sbatch_context(cfg, job_name=f"vasp_{args.round}_{structure_id}",
                              workdir=structure_dir, kind="vasp")
        sbatch_text = render_template("vasp.sbatch.template", ctx)
        sbatch_path = structure_dir / "submit.sbatch"
        sbatch_path.write_text(sbatch_text)

        if args.dry_run:
            eprint(f"[submit_vasp] (dry-run) rendered {sbatch_path}, not submitting")
            continue

        try:
            job_id = submit_job(sbatch_path)
            job_ids[structure_id] = job_id
            print(f"[submit_vasp] {structure_id}: submitted as job {job_id}")
        except RuntimeError as e:
            eprint(f"[submit_vasp] {structure_id}: {e}")

    write_json(vasp_round_dir / "job_ids.json", {"round": args.round, "cluster": args.cluster, "jobs": job_ids})
    print(f"[submit_vasp] Round {args.round}: submitted {len(job_ids)}/{len(manifest['structures'])} jobs on {args.cluster}")


if __name__ == "__main__":
    try:
        main()
    except ConfigError as e:
        eprint(f"[submit_vasp] CONFIG ERROR: {e}")
        sys.exit(2)
